### ISSUE TITLE
For blocking queries, request times out before Consul returns

### ISSUE THREAD

**Issue by AlecHFerguson** [hamishforbes/lua-resty-consul#15]
*So, first off, really love the module! This has made it so much easier to integration Consul into my OpenResty application. You've solved a lot of the tricky points, helped me understand Consul functionality and generally saved me a BUNCH of time. I'm gonna file a few issues here but overall, thank you!!!*

When making a query with the `wait` parameter, Consul still returns the value; thus, I would expect Resty Consul to return the value as well. However, I get a TCP Socket Read Timeout error:

```lua
2017/11/01 20:23:53 [info] 8#0: *13 [lua] maintenance.lua:133: Running continuous maintenance check, context: ngx.timer
2017/11/01 20:23:53 [debug] 8#0: *13 [lua] http.lua:631: send_request(): 
GET /v1/kv/frontgate/maintenance?index=2743&wait=15s HTTP/1.1
User-Agent: lua-resty-http/0.11 (Lua) ngx_lua/10010
Host: 10.20.21.122:8500

2017/11/01 20:24:08 [error] 8#0: *13 lua tcp socket read timed out, context: ngx.timer
2017/11/01 20:24:58 [info] 8#0: *13 [lua] maintenance.lua:143: res = null, err = "timeout", context: ngx.timer
```

It seems that the TCP socket timeout is being hit before Consul can return.

It looks like the TCP Socket Timeout is getting set to the wait time. I propose setting it to wait time + 1. I.E. change line 130 of `consul.lua` from this:

```lua
timeout = (opts.wait) * 1000
```

```lua
timeout = (opts.wait + 1) * 1000
```

It worked for me:

```
2017/11/01 20:29:20 [info] 6#0: *13 [lua] maintenance.lua:143: res = [{"LockIndex":0,"ModifyIndex":2743,"CreateIndex":2572,"Flags":0,"Value":"true","Key":"myapp\/maintenance"}], err = ["0","true","2743"], context: ngx.timer
```

I'm more than happy to submit a pull request if you'd like.

**Comment by Tieske** [comment]
@AlecHFerguson  Have you tested this?

I just started looking into Consul myself. I think the long-polling does indeed return a timeout. In your example above you have `wait=15s`, and the time between sending the request `20:23:53` and receiving the timeout at `20:24:08` is exactly the mentioned 15 seconds.

So the long-poll is timing out. The proper thing to do would in this case be to create a new (long-poll) request, and repeat that until a non-timeout error/value is returned.

And obviously this would then need to be a background process with probably a callback function that gets called with the changes.

**Comment by AlecHFerguson** [comment]
Thanks @Tieske ! I did test this. Based on the logs shown above, it appears it is the Lua TCP socket timing out and not Consul. When I changed `consul.lua` to wait `opts.wait + 1` seconds the request returned with the full JSON. I believe this is the expected behavior of Consul, to return the normal response at the end of the maximum wait duration. Though the docs are kinda ambiguous on this point.
https://www.consul.io/api/index.html#blocking-queries
https://www.consul.io/api/kv.html#read-key

Note that I am running in OpenResty, an Nginx implementation that embeds Lua. After researching further I found it was recommended to add the `lua_socket_log_errors off;` directive to your Nginx.conf file. Adding this worked for me.
https://github.com/openresty/lua-nginx-module#lua_socket_log_errors

Since I have a solution for my use case, I'm happy to close this ticket. If other folks encounter this issue then I would be happy to help find a solution.

**Comment by hamishforbes** [comment]
Ah yes it probably does make sense to increase the Lua side timeout to > the the wait period.  
Perhaps it would be best to set the socket timeout to `(wait_period * 1000) + configured_read_timeout)` rather than just adding an arbitrary magic number.

**Comment by AlecHFerguson** [comment]
I'd be happy to submit a PR. One line change if I'm just doing this. Though I may want to add unit tests as well. I'm pretty new to Lua -- Do you know of a good library to use for Lua unit testing?

**Comment by hamishforbes** [comment]
PR are always appreciated!

Most lua-resty-* modules make use of agentzh's Test::Nginx perl test suite.
See http://search.cpan.org/~agent/Test-Nginx-0.26/lib/Test/Nginx/Socket.pm
and https://github.com/pintsized/lua-resty-http/tree/master/t

**Comment by hamishforbes** [comment]
Closing in favour of #18
