### ISSUE TITLE
need help: the lua-resty-consul version outdate in luarocks

### ISSUE THREAD

**Issue by yongboy** [hamishforbes/lua-resty-consul#20]
Hi,

 Thank you for your code, I have used it online now  :))
 
 When I install it by luarocks as below:
 
```bash
luarocks install lua-resty-consul
```

I get v0.2 old version, lead to some errors in practice.

The new version is `v0.3.2`  in github, but in `luarocks.org` has old `v0.2` version, with homepage: https://luarocks.org/modules/hamish/lua-resty-consul.

So, please update the new version in luarocks.org, if you have time.

:))

PS:

Below is the `lua-resty-consul-0.3.2.rockspec` content:

```bash
# cat lua-resty-consul-0.3.2.rockspec

package = "lua-resty-consul"
version = "0.3-2"

source = {
  url = "git://github.com/hamishforbes/lua-resty-consul.git",
  tag = "v0.3.2",
}

description = {
  summary = "Library to interface with the consul HTTP API from ngx_lua",
  homepage = "https://github.com/hamishforbes/lua-resty-consul",
  maintainer = "hamish",
  license = "MIT",
}

dependencies = {
  "lua >= 5.1",
  "lua-resty-http",
}

build = {
  type = "builtin",
  modules = {
    ["resty.consul"] = "lib/resty/consul.lua",
  },
}
```

**Comment by hroost** [comment]
+1 would be nice to have this module updated in luarocks

**Comment by hamishforbes** [comment]
The latest version is available via OPM but I will try and have a look at doing luarocks again

**Comment by hamishforbes** [comment]
Done
