### ISSUE TITLE
why not expose X-Consul-Index?

### ISSUE THREAD

**Issue by davidbirdsong** [hamishforbes/lua-resty-consul#5]
Why return these other [headers](https://github.com/hamishforbes/lua-resty-consul/blob/master/lib/resty/consul.lua#L112)
and not the index or am I missing it somewhere else?

**Comment by cablehead** [comment]
I think it would be useful to return X-Consul-Index as well. 

- For KV queries, recurse=true, a number of values can be returned, and you current need to iterate through them to find the largest ModifiedIndex to poll with. 

- api endpoints like /health/service don't return ModifiedIndex in their payload - so it's not currently possible to long poll for these endpoints.

**Comment by hamishforbes** [comment]
Ah ok, that makes sense.

`X-Consul-Index` is now the 3rd element in the headers array returned from `get`.
I've also added some docs seeing as at least some other people are actually using this¬

**Comment by cablehead** [comment]
Sweet, thanks @hamishforbes!
