### ISSUE TITLE
Release on luarocks?

### ISSUE THREAD

**Issue by justicel** [hamishforbes/lua-resty-consul#7]
Howdy! Thanks for writing this. Do you think I could convince you to release a version of this on luarocks?

**Comment by hamishforbes** [comment]
Sure, ill take a look at that this morning.

**Comment by hamishforbes** [comment]
Done http://luarocks.org/modules/hamish/lua-resty-consul

**Comment by fititnt** [comment]
@hamishforbes can update? That version was a outdated

> 0.2-02 years ago17,390 downloads

**Comment by fititnt** [comment]
Hummm. So now is installed with this, not with luarocks with something like `opm get hamishforbes/lua-resty-consul`.

Maybe could be a good idea document how to install on the README.md
