### ISSUE TITLE
providing consul acl token

### ISSUE THREAD

**Issue by paperpunk** [hamishforbes/lua-resty-consul#9]
Hello,

is there an option to provide the consul acl token as part of the consul config?

thank you!

**Comment by freshvolk** [comment]
@paperpunk you can provide an acl token on a per-request basis by including it in the opts parameter:

```
local ok, err = consul:put('/kv/foobar', 'My key value!', { token = "some_token" })
if not ok then
    ngx.log(ngx.ERR, err)
end
```
Would make a request with the token `some_token`:

`/v1/kv/foobar?token=some_token`

**Comment by hamishforbes** [comment]
Closing in favour of #18
